# Generated by Django 6.0.7 on 2026-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_theme',
            field=models.CharField(choices=[('nord', 'Nord'), ('halloween', 'Halloween')], default='nord', max_length=20),
        ),
    ]
