# Generated by Django 6.0.7 on 2026-09-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
